<?php
/**
 * Bundled original template catalog.
 *
 * @package WooOptionsFic
 */

defined('ABSPATH') || exit;

return [
	[
		'slug' => 'design-your-own-pizza',
		'name' => __('Pizza configurator', 'wooptionsfic'),
		'description' => __('Let customers build their perfect pizza with crust, sauce, toppings, and cumulative pricing.', 'wooptionsfic'),
		'icon' => 'food',
		'category' => 'food',
		'categoryLabel' => __('Food', 'wooptionsfic'),
		'fieldCount' => 4,
		'features' => ['live_preview', 'conditional_logic', 'price_calculation'],
		'usage' => 2400,
		'popularity' => 98,
		'order' => 10,
	],
	[
		'slug' => 'personalized-apparel',
		'name' => __('Custom T-shirt builder', 'wooptionsfic'),
		'description' => __('Design custom apparel with colors, sizes, artwork uploads, print choices, and personalized text.', 'wooptionsfic'),
		'icon' => 'art',
		'category' => 'apparel',
		'categoryLabel' => __('Apparel', 'wooptionsfic'),
		'fieldCount' => 3,
		'features' => ['image_upload', 'live_preview', 'conditional_logic', 'price_calculation'],
		'usage' => 1800,
		'popularity' => 96,
		'order' => 9,
	],
	[
		'slug' => 'custom-furniture',
		'name' => __('Furniture customizer', 'wooptionsfic'),
		'description' => __('Configure materials, finishes, dimensions, and assembly services for made-to-order furniture.', 'wooptionsfic'),
		'icon' => 'admin-home',
		'category' => 'furniture',
		'categoryLabel' => __('Furniture', 'wooptionsfic'),
		'fieldCount' => 3,
		'features' => ['live_preview', 'conditional_logic', 'price_calculation'],
		'usage' => 620,
		'popularity' => 78,
		'order' => 8,
	],
	[
		'slug' => 'gift-box',
		'name' => __('Gift box builder', 'wooptionsfic'),
		'description' => __('Build the perfect gift box with products, wrapping, recipient details, and a personal message.', 'wooptionsfic'),
		'icon' => 'heart',
		'category' => 'gift',
		'categoryLabel' => __('Gift', 'wooptionsfic'),
		'fieldCount' => 4,
		'features' => ['live_preview', 'conditional_logic', 'price_calculation'],
		'usage' => 1100,
		'popularity' => 89,
		'order' => 7,
	],
	[
		'slug' => 'engraving',
		'name' => __('Engraving studio', 'wooptionsfic'),
		'description' => __('Create engraved products with text, font selection, preview styling, and per-character pricing.', 'wooptionsfic'),
		'icon' => 'edit',
		'category' => 'print',
		'categoryLabel' => __('Print', 'wooptionsfic'),
		'fieldCount' => 3,
		'features' => ['live_preview', 'conditional_logic', 'price_calculation'],
		'usage' => 930,
		'popularity' => 85,
		'order' => 6,
	],
	[
		'slug' => 'made-to-measure-curtains',
		'name' => __('Window configurator', 'wooptionsfic'),
		'description' => __('Configure curtains and window treatments with sizes, fabrics, finishes, and formula pricing.', 'wooptionsfic'),
		'icon' => 'editor-contract',
		'category' => 'windows-doors',
		'categoryLabel' => __('Windows & Doors', 'wooptionsfic'),
		'fieldCount' => 4,
		'features' => ['live_preview', 'conditional_logic', 'price_calculation'],
		'usage' => 750,
		'popularity' => 82,
		'order' => 5,
	],
	[
		'slug' => 'custom-computer',
		'name' => __('Computer customizer', 'wooptionsfic'),
		'description' => __('Customize computers with processors, memory, storage, graphics, accessories, and live pricing.', 'wooptionsfic'),
		'icon' => 'desktop',
		'category' => 'electronics',
		'categoryLabel' => __('Electronics', 'wooptionsfic'),
		'fieldCount' => 4,
		'features' => ['live_preview', 'conditional_logic', 'price_calculation'],
		'usage' => 1600,
		'popularity' => 94,
		'order' => 4,
	],
	[
		'slug' => 'rental-request',
		'name' => __('Rental booking form', 'wooptionsfic'),
		'description' => __('Book rental products and services with date ranges, pickup times, quantities, and add-ons.', 'wooptionsfic'),
		'icon' => 'calendar-alt',
		'category' => 'services',
		'categoryLabel' => __('Services', 'wooptionsfic'),
		'fieldCount' => 3,
		'features' => ['conditional_logic', 'price_calculation'],
		'usage' => 860,
		'popularity' => 81,
		'order' => 3,
	],
	[
		'slug' => 'donation',
		'name' => __('Donation campaign', 'wooptionsfic'),
		'description' => __('Accept bounded customer-defined donations with suggested amounts and a personal dedication.', 'wooptionsfic'),
		'icon' => 'money-alt',
		'category' => 'services',
		'categoryLabel' => __('Services', 'wooptionsfic'),
		'fieldCount' => 2,
		'features' => ['conditional_logic', 'price_calculation'],
		'usage' => 540,
		'popularity' => 72,
		'order' => 2,
	],
	[
		'slug' => 'team-roster',
		'name' => __('Team roster builder', 'wooptionsfic'),
		'description' => __('Collect repeatable player names, sizes, jersey numbers, roles, and personalization choices.', 'wooptionsfic'),
		'icon' => 'groups',
		'category' => 'apparel',
		'categoryLabel' => __('Apparel', 'wooptionsfic'),
		'fieldCount' => 1,
		'features' => ['repeaters', 'conditional_logic', 'price_calculation'],
		'usage' => 430,
		'popularity' => 68,
		'order' => 1,
	],
];
